Repository bnb-chain/bsc, pull requests merged in 2022-08, with the labels that each got.

#1044 ci: add commit message lint
  .github/commitlint.config.js
  .github/workflows/commit-lint.yml
  docs/lint/commit.md
Labels: r4r

#1053 state: fix offline tool start failed when start with pruneancient
  cmd/geth/pruneblock_test.go
  cmd/utils/flags.go
  core/blockchain_repair_test.go
  core/blockchain_sethead_test.go
  core/blockchain_snapshot_test.go
  core/blockchain_test.go
  core/rawdb/accessors_chain_test.go
  core/rawdb/database.go
  core/state/pruner/pruner.go
  eth/downloader/downloader_test.go
  node/node.go
Labels: r4r

#1051 Implement BEP153: Native Staking
  core/state_processor_test.go
  core/systemcontracts/const.go
  core/systemcontracts/upgrade.go
  eth/gasprice/gasprice_test.go
  params/config.go
Labels: r4r

#1057 ci: allow merge pull request
  .github/commitlint.config.js
Labels: enhancement, r4r

#1062 test: fix TestOfflineBlockPrune
  build/ci.go
  cmd/geth/pruneblock_test.go
Labels: r4r

#1060 consensus: fix the GasLimitBoundDivisor
  consensus/misc/eip1559_test.go
  consensus/parlia/parlia.go
  core/block_validator_test.go
  params/protocol_params.go
Labels: r4r

#1063 ci: fix the pattern of commit lint
  .github/commitlint.config.js
Labels: r4r

#1061 fix: upstream patches
  appveyor.yml
  build/ci.go
  cmd/geth/snapshot.go
  core/blockchain.go
  core/rawdb/accessors_state.go
  core/state/pruner/pruner.go
  core/state/state_object.go
  core/state/statedb.go
  core/vm/operations_acl.go
  eth/downloader/downloader.go
  eth/protocols/snap/sync.go
  eth/tracers/api.go
  graphql/graphql.go
  internal/build/download.go
  internal/ethapi/api.go
  les/vflux/client/fillset_test.go
  les/vflux/server/clientpool.go
  light/lightchain.go
  mobile/geth.go
  p2p/server.go
  rpc/server_test.go
  tests/fuzzers/vflux/clientpool-fuzzer.go
  trie/iterator.go
  trie/iterator_test.go
Labels: r4r

#1070 txpool: reheap the priced list if london fork not enabled
  core/tx_pool.go
Labels: bug, r4r

#1006 statedb: get rid of activestate, stopPrefetcher manually
  core/blockchain.go
  core/state/statedb.go
Labels: enhancement, r4r

#1066 fix: update cross chain logic of native stake
  core/systemcontracts/upgrade.go
  params/config.go
Labels: r4r

#1073 upgrade: update version and CHANGELOG.md
  CHANGELOG.md
  params/version.go
Labels: r4r
